### PR TITLE
Upgrade to KDE6

### PR DESCRIPTION
**Pull request by snoweuph**
currently a WIP

### CODE REVIEW

**Comment by snoweuph** [comment]
@bikass what is the difference between the release 6 & the release 6.4 on the KDE Store?

**Comment by snoweuph** [comment]
So I looked at the Diff, and it looks like youre baking some stuff specificly for plasma?

do you have a tool for that, or how could I approach that myselve?

Still need to Fix the Clipboard Icon, which uses the Klippy Icon Instead of the fitting Tray Icon

**Comment by snoweuph** [comment]
I looked a bit around, and found this:
https://github.com/coderhisham/Futura-Icon-Pack
which is actively worked on the KDE store.

In that Theme all the Icons Except the Clipboard Icon, but that was a really easy fix.
image

**Comment by bikass** [comment]
Hi, I guess it still not solved in kora :) . You need to create symlinks not rename, because those icons might be used in other DE's.

**Pull request closed without merging**
